freebsd_instance:
  image_family: freebsd-11-3-snap

task:
  name: FreeBSD
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
  cargo_cache:
    folder: $HOME/.cargo/registry
  build_script:
    - . $HOME/.cargo/env
    - cargo build
    - cargo build --no-default-features
  test_script:
    - . $HOME/.cargo/env
    - RUST_BACKTRACE=1 cargo test
    - cargo test --no-default-features
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
