[package]

name = "mio"
version = "0.0.1"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
time = "*"

[dependencies.nix]

git = "file:///home/rick/Projects/nix-rust"

[[test]]

name = "test"
path = "test/test.rs"
