[package]

name = "mio"
version = "0.2.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
nix = "0.2.0"
log = "0.2.3"
time = "0.1.16"
bytes = "0.1.2"
bitflags = "0.1"

[dev-dependencies]
env_logger = "0.2.2"

[[test]]

name = "test"
path = "test/test.rs"
