[package]
edition = "2018"
name = "mio"
# When releasing to crates.io:
# - Update html_root_url.
# - Update CHANGELOG.md.
# - Update doc URL.
# - Create git tag
version       = "0.7.0"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "https://docs.rs/mio/0.7.0/mio/"
homepage      = "https://github.com/tokio-rs/mio"
repository    = "https://github.com/tokio-rs/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
]
publish = false

[features]

[dependencies]
iovec = "0.1.2"
log   = "0.4.6"
net2  = "0.2.33"
slab  = "0.4.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.58"

[target.'cfg(windows)'.dependencies]
miow   = "0.3.3"
winapi = { version = "0.3", features = ["winsock2"] }
ntapi  = "0.3"

[dev-dependencies]
bytes      = "0.4.12"
env_logger = { version = "0.6.1", default-features = false }
tempdir    = "0.3.7"
