[package]

name          = "mio"
version       = "0.6.11"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "https://docs.rs/mio"
homepage      = "https://github.com/carllerche/mio"
repository    = "https://github.com/carllerche/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
]

[features]
with-deprecated = []
default = ["with-deprecated"]

[dependencies]
lazycell = "0.6.0"
log      = "0.3.1"
slab     = "0.3.0"
net2     = "0.2.29"
iovec    = "0.1.1"

[target.'cfg(target_os = "fuchsia")'.dependencies]
fuchsia-zircon = "0.2.1"
fuchsia-zircon-sys = "0.2.0"

[target.'cfg(unix)'.dependencies]
libc   = "0.2.19"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["std", "ioapiset", "winbase", "winerror"] }
miow   = "0.3.1"

[dev-dependencies]
env_logger = { version = "0.4.0", default-features = false }
tempdir    = "0.3.4"
bytes      = "0.3.0"

[[test]]
name = "test"
path = "test/mod.rs"

[replace]
"iovec:0.1.1" = { git = "https://github.com/steffengy/iovec.git" }
