[package]

name          = "mio"
version       = "0.5.0-pre"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "http://rustdoc.s3-website-us-east-1.amazonaws.com/mio/v0.4.x/mio/"
homepage      = "https://github.com/carllerche/mio"
repository    = "https://github.com/carllerche/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
log   = "0.3.1"
nix   = { git = "https://github.com/carllerche/nix-rust", rev = "f37e45628e" }
libc  = "0.1.8"
slab  = "0.1.0"
clock_ticks = "0.0.5"
bytes = { git = "https://github.com/carllerche/bytes", rev = "7edb577d0a" }
winapi = "0.2.1"
wio = { git = "https://github.com/alexcrichton/wio" }
net2 = "0.2.11"

[dev-dependencies]
env_logger = "0.3.0"
tempdir    = "0.3.4"

[[test]]
name = "test"
path = "test/test.rs"

[[test]]
name = "tcp"
path = "test/tcp.rs"

[[test]]
name = "smoke"
path = "test/smoke.rs"
