[package]

name = "mio"
version = "0.0.1"
authors = ["Carl Lerche <me@carllerche.com>", "Clark Gaebel <cgaebel@mozilla.com>", "Vlad Kluev <vkluev@fb.com>"]

[dependencies.nix]

git = "https://github.com/cgaebel/nix-rust"

[[test]]

name = "test"
path = "test/test.rs"
