jobs:
- job: ${{ parameters.name }}
  displayName: Clippy

  pool:
    vmImage: ubuntu-16.04

  steps:
    - template: azure-install-rust.yml
      parameters:
        rust_version: stable

    - script: rustup component add clippy
      displayName: "Add component"

    # TODO: remove allowing `match-like-matches-macro`, once the minimum Rust
    # version >= 1.42 (currently 1.39).
    - script: cargo clippy --all-targets --all-features -- -D warnings -A clippy::cognitive-complexity -A clippy::match_like_matches_macro
      displayName: "Run Clippy"
